<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [1]:
import numpy as np

In [2]:
#1 
a = [1,1,1]
b = [3,3,3]
A = np.array(a)
B = np.array(b)

x1 = np.subtract(B,A)
print("Операция 1 =",x1)
x2 = np.divide(B,2)
print("Операция 2 =",x2)
x3 = np.transpose(x2)
print("Операция 3 =",x3)
x4 = np.multiply(x1,x3)
print("Операция 4 =",x4)

answer = x4[0]+x4[1]+x4[2]

print("Ответ:",-answer)

Операция 1 = [2 2 2]
Операция 2 = [1.5 1.5 1.5]
Операция 3 = [1.5 1.5 1.5]
Операция 4 = [3. 3. 3.]
Ответ: -9.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [3]:
#2. Ваш код здесь

A = np.zeros((8,8))

A[7] = [4, 3, 2, 6, 5, 2, 3, 4]
A[0] = -A[7]
A[6] = [1, 1, 1, 1, 1, 1, 1, 1]
A[1] = -A[6]

print(A)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [4]:
# 3. Ваш код здесь
Mas = np.arange(2, 21, 2)  # Четные числа от 2 до 20
NMas = Mas + 1      # Ближайшие к ним более большие нечетные числа

result = Mas * NMas
print(result)

[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [20]:
# 4. Ваш код здесь

arr = np.random.uniform(low=0.0, high=20.0, size=(4, 7))

print("До нормализации:\n\n",arr)

arr_normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

arr_normalized_rounded = np.round(arr_normalized, decimals=4)

print("\nПосле нормализации:\n\n",arr_normalized_rounded)


До нормализации:

 [[13.79028147 16.94003094  7.79077071  1.10759539 12.38942627 11.58101369
   6.34615119]
 [ 6.65426304 14.34632239  5.86878273 12.08562782 10.56174605  5.97715861
   0.9459266 ]
 [ 4.50239008 18.0839983  19.45294793 16.33491426 13.45011623 14.12599855
   2.37228229]
 [ 1.11225705  2.28885841  2.77582581 12.00053766  8.51734624  7.21516331
  12.66263618]]

После нормализации:

 [[0.694  0.8642 0.3699 0.0087 0.6183 0.5747 0.2918]
 [0.3084 0.7241 0.266  0.6019 0.5196 0.2719 0.    ]
 [0.1922 0.926  1.     0.8315 0.6756 0.7122 0.0771]
 [0.009  0.0726 0.0989 0.5973 0.4091 0.3387 0.6331]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [6]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

final_array = np.zeros((3,3))

i = 1
i_arr = 0

while i <= 3:
    j = 1
    j_arr = 0
    while j <=3:
        final_array[i_arr][j_arr] = my_array[i][j]
        j += 1
        j_arr += 1
    i += 1
    i_arr += 1
    
print(final_array)

[[ 7.  8.  9.]
 [12. 13. 14.]
 [17. 18. 19.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [7]:
# 6. Ваш код здесь

my_sin = np.sin(my_array)
my_sin_rounded = np.round(my_sin, decimals=3)

summ = 0
summ2 = 0

for elem in my_sin_rounded:
    summ += elem
for elem in summ:
    summ2 += elem

print(f"Массив my_sin:\n{my_sin_rounded}\n")
print(f"Сумма элементов массива: {round(summ2,3)}\n")

Массив my_sin:
[[ 0.841  0.909  0.141 -0.757 -0.959]
 [-0.279  0.657  0.989  0.412 -0.544]
 [-1.    -0.537  0.42   0.991  0.65 ]
 [-0.288 -0.961 -0.751  0.15   0.913]
 [ 0.837 -0.009 -0.846 -0.906 -0.132]]

Сумма элементов массива: -0.059



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [21]:
# 7. Ваш код здесь

my_matrix =  np.random.uniform(low=0.0, high=100.0, size=(20, 1))
print(np.round(my_matrix, decimals = 2))

sorted_matrix = np.sort(my_matrix, axis=None)[::-1]
second_max_value = sorted_matrix[1]

ind = np.where(my_matrix == second_max_value)

print("Второе сверху значение:", second_max_value)
print("Индекс второго сверху значения:", ind)

[[33.2 ]
 [62.89]
 [85.84]
 [30.09]
 [71.39]
 [81.64]
 [31.04]
 [37.61]
 [87.81]
 [65.87]
 [81.2 ]
 [24.5 ]
 [70.82]
 [93.62]
 [56.97]
 [22.01]
 [72.  ]
 [93.87]
 [18.33]
 [10.49]]
Второк сверху значение: 93.61660035040119
Индекс второго сверху значения: (array([13]), array([0]))


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [9]:
# 8. Ваш код здесь
ar1 = np.random.uniform(low=0, high=10, size=(4, 7))
ar2 = np.random.uniform(low=0, high=10, size=(4, 7))

print("ar1:\n",np.round(ar1,decimals = 2))
print("\nar2:\n",np.round(ar2,decimals = 2))

ar3 = np.zeros((4,7))

oper = input("\nВведите номер операции для заполнения массива (1 - максимум, 2 - минимум, 3 - среднее): ")

if oper == "1":
    i = 0
    while i < 4:
        j = 0
        while j < 7:
            ar3[i][j] = max(ar1[i][j],ar2[i][j])
            j += 1
        i +=1
elif oper == "2":
    i = 0
    while i < 4:
        j = 0
        while j < 7:
            ar3[i][j] = min(ar1[i][j],ar2[i][j])
            j += 1
        i +=1
elif oper == "3":
    i = 0
    while i < 4:
        j = 0
        while j < 7:
            ar3[i][j] = np.add(ar1[i][j],ar2[i][j])/2
            j += 1
        i +=1
print("\nar3:", np.round(ar3,decimals = 2))

ar1:
 [[4.67 5.34 5.15 7.84 6.96 7.01 9.36]
 [7.29 4.35 5.36 5.84 0.02 1.12 3.99]
 [3.24 3.91 9.79 3.64 4.29 4.67 8.97]
 [9.74 5.21 9.92 1.34 6.79 3.61 5.62]]

ar2:
 [[0.74 8.51 0.1  0.53 4.09 1.75 7.9 ]
 [1.81 4.19 0.97 1.9  8.84 3.65 0.74]
 [4.7  7.7  5.78 8.   2.71 4.92 2.98]
 [5.1  8.43 8.96 8.83 7.68 3.16 0.79]]

Введите номер операции для заполнения массива (1 - максимум, 2 - минимум, 3 - среднее): 3

ar3: [[2.7  6.93 2.62 4.18 5.53 4.38 8.63]
 [4.55 4.27 3.17 3.87 4.43 2.39 2.36]
 [3.97 5.81 7.79 5.82 3.5  4.79 5.98]
 [7.42 6.82 9.44 5.08 7.23 3.38 3.2 ]]


In [10]:
# 8. Ваш код здесь

def CreateMatrix(array1, array2, operator):
    result = np.zeros((4,7))
    if operator == "1":
        result = max(array1,array2)
    elif operator == "2":
        result = min(array1,array2)
    elif operator == "3":
        result = np.add(array1,array2)/2
    return result
    


ar1 = np.random.uniform(low=0, high=10, size=(4, 7))
ar2 = np.random.uniform(low=0, high=10, size=(4, 7))

print("ar1:\n",np.round(ar1,decimals = 2))
print("\nar2:\n",np.round(ar2,decimals = 2))

ar3 = np.zeros((4,7))

oper = input("\nВведите номер операции для заполнения массива (1 - максимум, 2 - минимум, 3 - среднее): ")


i = 0
while i < 4:
    j = 0
    while j < 7:
        ar3[i][j] = CreateMatrix(ar1[i][j],ar2[i][j],oper)
        j += 1
    i +=1

print("\nar3:", np.round(ar3,decimals = 2))

ar1:
 [[0.63 4.64 3.42 7.54 7.03 7.61 1.62]
 [9.41 0.94 5.62 0.78 0.87 9.87 3.46]
 [2.8  8.34 8.64 3.26 3.61 0.9  6.74]
 [3.67 7.11 6.76 4.76 0.59 8.   2.21]]

ar2:
 [[4.8  9.57 7.4  2.04 2.67 4.34 9.7 ]
 [7.94 9.97 0.69 5.18 2.18 1.39 1.9 ]
 [2.41 5.67 7.7  0.51 9.61 2.09 5.21]
 [6.46 3.16 2.97 7.11 9.85 5.64 8.1 ]]

Введите номер операции для заполнения массива (1 - максимум, 2 - минимум, 3 - среднее): 3

ar3: [[2.71 7.1  5.41 4.79 4.85 5.98 5.66]
 [8.68 5.45 3.16 2.98 1.52 5.63 2.68]
 [2.6  7.   8.17 1.89 6.61 1.5  5.98]
 [5.07 5.14 4.86 5.94 5.22 6.82 5.16]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [11]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

#print(great_array)

sum_greater_than_50 = np.sum(great_array[great_array > 50])
print(sum_greater_than_50)

5470.0


- great_array > 50 создает булев массив той же формы, что и great_array, где элементы, удовлетворяющие условию больше 50, будут равны True, а остальные элементы будут равны False.
- great_array[great_array > 50] использует этот булев массив в качестве маски для выбора элементов из great_array, которые удовлетворяют условию больше 50. Таким образом, мы получим одномерный массив только из элементов, которые больше 50.
- np.sum(...) вычисляет сумму всех элементов этого одномерного массива. 

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [12]:
# 10. Ваш код здесь

reshape_array = great_array.reshape(1,-1)
#print(reshape_array)

print("Элемент с индексом 150 равен", reshape_array[0][150])

Элемент с индексом 150 равен 7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [13]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь

C = np.where(A == B)[0]
print(C)

[1 3 5 7]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [15]:
# 12.  Ваш код здесь

M1 = np.arange(2, 21, 2)  # Четные числа от 2 до 20
M2 = M1 + 1      # Ближайшие к ним более большие нечетные числа

M3 = np.multiply(M1,M2)

M4 = np.column_stack((M1,M2,M3))

print(M4)

[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
